In [1]:
from scipy.spatial import distance as dist
import numpy as np

In [2]:
np.random.seed(42)

In [6]:
objectCentroids = np.random.uniform(size=(2,2))
centroids = np.random.uniform(size=(3,2))
objectCentroids, centroids

(array([[0.21233911, 0.18182497],
        [0.18340451, 0.30424224]]),
 array([[0.52475643, 0.43194502],
        [0.29122914, 0.61185289],
        [0.13949386, 0.29214465]]))

In [7]:
D = dist.cdist(objectCentroids, centroids)
D.shape, D

((2, 3),
 array([[0.40020573, 0.43720436, 0.13220009],
        [0.36445731, 0.32596083, 0.04554665]]))

In [10]:
D.min(axis=1)

array([0.13220009, 0.04554665])

In [11]:
rows = D.min(axis=1).argsort();rows

array([1, 0])

In [14]:
D.argmin(axis=1)

array([2, 2])

In [15]:
cols = D.argmin(axis=1)[rows]; cols

array([2, 2])

In [ ]:
vid = ''